#pragma once
#include <stdint.h>
#include "FontDef.h"

enum class SymbolIcon : char
{
    Empty = 48,
    Wifi,
    Smyle,
    Influx,
};

// --------------------------------------------------------
// Generated by Font Editor
// https://vanbassum.github.io/FontEditor/
// Font: font8x8sym
// Width: 8
// Height: 8
// Chars: 48..51 (4)
// --------------------------------------------------------

static const uint8_t font8x8sym_charset[4][8] = {
    { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }, // '0' (48)
    { 0x04, 0x02, 0x09, 0x65, 0x65, 0x09, 0x02, 0x04 }, // '1' (49)
    { 0x3C, 0x42, 0x95, 0xA1, 0xA1, 0x95, 0x42, 0x3C }, // '2' (50)
    { 0x74, 0x32, 0x51, 0x81, 0x81, 0x8A, 0x4C, 0x2E }, // '3' (51)
};

static const FontDef font8x8sym = {
    .table = (const uint8_t*)font8x8sym_charset,
    .width = 8,
    .height = 8,
    .firstChar = 48,
    .lastChar = 51,
};
